services:
  - type: web
    name: hoa-hoc-8
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_GROQ_API_KEY
        fromSecret:
          name: groq_api_key_secret
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
